MxOnline/urls.py
# encoding: utf8

"""MxOnline URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Import the include() function: from django.conf.urls import url, include
    3. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
'''django自带模块'''
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView   #引入django自带的TemplateView,用于直接处理静态文件
from django.views.static import serve        # 用于处理静态文件


'''第三方模块'''
# 引入xadmin
import xadmin
from MxOnline.settings import MEDIA_ROOT    #, STATIC_ROOT


'''自定义模块'''
from users.views import IndexView, LoginView, LogoutView, RegisterView, ActivateUserView, ForgetPwdView, \
    ShowPwdResetView, PwdResetView

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^xadmin/', xadmin.site.urls),    # 把默认的admin 换成 xadmin
    url(r'^captcha/', include('captcha.urls')),     #第三方的图片验证码生成器，需要加上它的url

    # 使用TemplateView， 不用写view函数，直接处理 xx.html 等网页文件
    # url(r'^$', TemplateView.as_view(template_name="index.html"), name="index"),

    url(r'^$', IndexView.as_view(), name="index"),
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    url(r'^register/$', RegisterView.as_view(), name="register"),
    url(r'^activate/(?P<activate_code>.*)/$', ActivateUserView.as_view(), name="user_activate"),
    url(r'^forgetpwd/$', ForgetPwdView.as_view(), name="forget_pwd"),
    url(r'^showpwdreset/(?P<reset_code>.*)/$', ShowPwdResetView.as_view(), name="show_pwd_reset"),
    url(r'^pwdreset/$', PwdResetView.as_view(), name="pwd_reset"),

    # 设置上传文件的访问处理(注意路径 ^uploads 要和settings.py 里的 MEDIA_URL 对应)
    url(r'^uploads/(?P<path>.*)$', serve, {"document_root":MEDIA_ROOT}),

    # 处理静态文件（当settings.py设置DEBUG = False 时）
    # url(r'^static/(?P<path>.*)$', serve, {"document_root":STATIC_ROOT}),

    # 导入各个app的urls.py
    url(r'^org/', include('organizations.urls', namespace='org')),    # 课程机构URL配置
    url(r'^course/', include('courses.urls', namespace='course')),    # 课程相关URL配置
    url(r'^user/', include('users.urls', namespace='user')),  # 用户URL配置
]

# 全局404和500页面配置(注意：类似 handler404 这些变量名称是固定的)
handler404 = 'users.views.page_not_found'
handler500 = 'users.views.page_error'

apps/courses/urls.py
# encoding: utf8
__author__ = 'xuan'
__date__ = '2017/8/23 10:56'

'''导入django自带模块'''
from django.conf.urls import url, include

'''导入第三方模块'''

'''导入自定义模块'''
from views import CourseListView, CourseDetailView, CourseInfoView, CourseCommentsView, \
    CourseAddCommentsView, CourseVideoPlayView


'''自定义URL'''
urlpatterns = [
    url(r'^list/$', CourseListView.as_view(), name="course_list"),  # 课程列表
    url(r'^detail/(?P<course_id>\d+)/$', CourseDetailView.as_view(), name="course_detail"),  # 课程详情页
    url(r'^info/(?P<course_id>\d+)/$', CourseInfoView.as_view(), name="course_info"),  # 章节信息
    url(r'^comments/(?P<course_id>\d+)/$', CourseCommentsView.as_view(), name="course_comments"),  # 查看课程评论
    url(r'^add_comments/$', CourseAddCommentsView.as_view(), name="course_add_comments"),  # 添加课程评论
    url(r'^videoplay/(?P<video_id>\d+)/$', CourseVideoPlayView.as_view(), name="video_play"),  # 课程视频播放页
]

apps/organizations/urls.py
# encoding: utf8
__author__ = 'xuan'
__date__ = '2017/8/23 10:56'

'''导入django自带模块'''
from django.conf.urls import url, include


'''导入第三方模块'''


'''导入自定义模块'''
from views import OrgListView, AddUserAskView, OrgHomeView, OrgCourseView, OrgDescView, \
    OrgTeacherView, AddFavView, TeacherListView, TeacherDetailView



'''自定义URL'''
urlpatterns = [
    url(r'^list/$', OrgListView.as_view(), name="org_list"),  # 课程机构列表
    url(r'^add_ask/$', AddUserAskView.as_view(), name="add_ask"),  # 用户添加咨询
    url(r'^home/(?P<org_id>\d+)/$', OrgHomeView.as_view(), name="org_home"),  # 用户添加咨询
    url(r'^course/(?P<org_id>\d+)/$', OrgCourseView.as_view(), name="org_course"),  # 机构课程列表
    url(r'^desc/(?P<org_id>\d+)/$', OrgDescView.as_view(), name="org_desc"),  # 机构介绍
    url(r'^teacher/(?P<org_id>\d+)/$', OrgTeacherView.as_view(), name="org_teacher"),  # 机构讲师
    url(r'^add_fav/$', AddFavView.as_view(), name="add_fav"),  # 机构或课程的收藏与取消

    # 讲师相关URL
    url(r'^teacher/list/$', TeacherListView.as_view(), name="teacher_list"),  # 讲师列表页
    url(r'^teacher/detail/(?P<teacher_id>\d+)/$', TeacherDetailView.as_view(), name="teacher_detail"),  # 讲师详情页
]

apps/users/urls.py
# encoding: utf8
__author__ = 'xuan'
__date__ = '2017/8/23 10:56'

'''导入django自带模块'''
from django.conf.urls import url, include


'''导入第三方模块'''


'''导入自定义模块'''
from views import UserInfoView, UserImageUploadView, UserPwdUpdateView, UserSendEmailUpdateCodeView, \
    UserEmailUpdateView, MyCourseView, MyFavOrgView, MyFavTeacherView, MyFavCourseView, MyMessageView



'''自定义URL'''
urlpatterns = [
    url(r'^info/$', UserInfoView.as_view(), name="user_info"),  #用户信息查看与保存
    url(r'^image/upload/$', UserImageUploadView.as_view(), name="user_image_upload"),  #用户信息
    url(r'^pwd/update/$', UserPwdUpdateView.as_view(), name="user_pwd_update"),  # 用户个人中心更改密码
    url(r'^send_emailupdate_code/$', UserSendEmailUpdateCodeView.as_view(), name="user_send_emailupdate_code"),  # 发送修改邮箱验证码
    url(r'^email_update/$', UserEmailUpdateView.as_view(), name="user_email_update"),  # 修改邮箱
    url(r'^mycourse/$', MyCourseView.as_view(), name="user_mycourse"),  # 我的课程
    url(r'^myfav/org/$', MyFavOrgView.as_view(), name="user_myfav_org"),  # 我收藏的课程机构
    url(r'^myfav/teacher/$', MyFavTeacherView.as_view(), name="user_myfav_teacher"),  # 我收藏的讲师
    url(r'^myfav/course/$', MyFavCourseView.as_view(), name="user_myfav_course"),  # 我收藏的课程
    url(r'^mymessage/$', MyMessageView.as_view(), name="user_mymessage"),  # 我的消息
]

apps/courses/models.py
# encoding: utf8
from __future__ import unicode_literals

'''导入python/django自带模块'''
from datetime import datetime
from django.db import models


'''导入第三方模块'''


'''导入自定义模块'''
from organizations.models import CourseOrg, Teacher




'''自定义Model'''
class Course(models.Model):
    name = models.CharField(max_length=50, verbose_name=u'课程名')
    desc = models.CharField(max_length=300, verbose_name=u'课程描述')
    detail = models.TextField(verbose_name=u'课程详情')
    notice = models.CharField(max_length=200, verbose_name=u"课程公告", default="")
    is_banner = models.BooleanField(default=False, verbose_name=u"是否轮播")
    degree = models.CharField(max_length=2, verbose_name=u"难度", choices=(("L", u"初级"), ("M", u"中级"), ("H", u"高级")))
    learn_times = models.IntegerField(default=0, verbose_name=u"学习时长(分钟)")
    students = models.IntegerField(default=0 ,verbose_name=u"学习人数")
    fav_num = models.IntegerField(default=0 ,verbose_name=u"收藏人数")
    image = models.ImageField(upload_to="courses/%Y/%m", verbose_name=u"封面图", max_length=100)
    category = models.CharField(default="", max_length=20, verbose_name=u"课程类别")
    tag = models.CharField(max_length=20, verbose_name=u"课程标签", default="")
    click_num = models.IntegerField(default=0, verbose_name=u"点击数")
    must_know = models.CharField(max_length=300, verbose_name=u'课程须知', default="")
    what_you_learn = models.CharField(max_length=300, verbose_name=u'你能学到什么', default="")
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"添加时间")

    # 外键
    course_org = models.ForeignKey(CourseOrg, verbose_name=u"课程机构", null=True, blank=True)
    teacher = models.ForeignKey(Teacher, verbose_name=u"讲师", null=True, blank=True)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = u"课程"
        verbose_name_plural = verbose_name

    # 反向获取本课程的章节数
    def get_lesson_num(self):
        return self.lesson_set.all().count()

    # 反向获取学习本课程的5个用户
    def get_user_courses(self):
        return self.usercourse_set.all()[:5]

    # 反向获取本课程的所有章节
    def get_course_lessons(self):
        return self.lesson_set.all()



class Lesson(models.Model):
    name = models.CharField(max_length=100, verbose_name=u"章节名")
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"添加时间")

    # 外键
    course = models.ForeignKey(Course, verbose_name=u"课程")

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = u"章节"
        verbose_name_plural = verbose_name

    # 反向获取本章节的所有视频
    def get_lesson_videos(self):
        return self.video_set.all()


class Video(models.Model):
    name = models.CharField(max_length=100, verbose_name=u"视频名")
    learn_times = models.IntegerField(default=0, verbose_name=u"学习时长(分钟)")
    url = models.CharField(max_length=200, verbose_name=u"访问地址", default="")
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"添加时间")

    # 外键
    lesson = models.ForeignKey(Lesson, verbose_name=u"章节")

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = u"视频"
        verbose_name_plural = verbose_name


class CourseResource(models.Model):
    name = models.CharField(max_length=100, verbose_name=u"名称")
    download = models.FileField(upload_to="courses/%Y/%m", verbose_name=u"资源文件", max_length=100)
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"添加时间")

    # 外键
    course = models.ForeignKey(Course, verbose_name=u"课程")

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = u"课程资源"
        verbose_name_plural = verbose_name

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}首页 - 萌学在线网{% endblock %}

{% block css %}
{#    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/base.css' %}"/>#}
{#    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/learn-less.css' %}"/>#}
{#    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/common-less.css' %}">#}
{% endblock %}

{% block bread %}
{% endblock %}

{% block content %}

    <div class="banner">
        <div class="wp">
            <div class="fl">
                <div class="imgslide">
                    <ul class="imgs">
                        {% for banner in all_banners %}
                            <li>
                                <a href="{{ MEDIA_URL }}{{ banner.url }}">
                                    <img width="1200" height="478"
                                         src="{{ MEDIA_URL }}{{ banner.image }}"/>
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="unslider-arrow prev"></div>
                <div class="unslider-arrow next"></div>
            </div>

        </div>

    </div>
    <!--banner end-->
    <!--feature start-->
    <section>
        <div class="wp">
            <ul class="feature">
                <li class="feature1">
                    <img class="pic" src="{% static 'images/feature1.png' %}"/>
                    <p class="center">专业权威</p>
                </li>
                <li class="feature2">
                    <img class="pic" src="{% static 'images/feature2.png' %}"/>
                    <p class="center">课程最新</p>
                </li>
                <li class="feature3">
                    <img class="pic" src="{% static 'images/feature3.png' %}"/>
                    <p class="center">名师授课</p>
                </li>
                <li class="feature4">
                    <img class="pic" src="{% static 'images/feature4.png' %}"/>
                    <p class="center">数据真实</p>
                </li>
            </ul>
        </div>
    </section>
    <!--feature end-->
    <!--module1 start-->
    <section>
        <div class="module">
            <div class="wp">
                <h1>公开课程</h1>
                <div class="module1 eachmod">
                    <div class="module1_1 left">
                        <img width="228" height="614" src="{% static 'images/module1_1.jpg' %}"/>
                        <p class="fisrt_word">名师授课<br/>专业权威</p>
                        <a class="more" href="{% url 'course:course_list' %}">查看更多课程 ></a>
                    </div>
                    <div class="right group_list">
                        <div class="module1_2 box">
                            <div class="imgslide2">
                                <ul class="imgs">
                                    {% for banner_course in banner_courses %}
                                        <li>
                                            <a href="{% url 'course:course_detail' banner_course.id %}">
                                                <img width="470" height="300"
                                                     src="{{ MEDIA_URL }}{{ banner_course.image }}"/>
                                            </a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                            <div class="unslider-arrow2 prev"></div>
                            <div class="unslider-arrow2 next"></div>
                        </div>
                        {% for course in courses %}
                            <div class="module1_{{ forloop.counter|add:2 }} box">
                                <a href="{% url 'course:course_detail' course.id %}">
                                    <img width="233" height="190" src="{{ MEDIA_URL }}{{ course.image }}"/>
                                </a>
                                <div class="des">
                                    <a href="{% url 'course:course_detail' course.id %}">
                                        <h2 title="django入门">{{ course.name }}</h2>
                                    </a>
                                    <span class="fl">难度：<i class="key">{{ course.get_degree_display }}</i></span>
                                    <span class="fr">学习人数：{{ course.students }}</span>
                                </div>
                                <div class="bottom">
                                    <span class="fl" title="慕课网">{{ course.course_org.name }}</span>
                                    <span class="star fr">{{ course.fav_num }}</span>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="module greybg">
            <div class="wp">
                <h1>课程机构</h1>
                <div class="module3 eachmod">
                    <div class="module3_1 left">
                        <img width="228" height="463" src="{% static 'images/module3_1.jpg' %}"/>
                        <p class="fisrt_word">名校来袭<br/>权威认证</p>
                        <a class="more" href="{% url 'org:org_list' %}">查看更多机构 ></a>
                    </div>
                    <div class="right">
                        <ul>
                            {% for org in course_orgs %}
                                <li class="{% if forloop.counter|divisibleby:5 %}five{% endif %}">
                                    <a href="{% url 'org:org_home' org.id %}">
                                        <div class="company">
                                            <img width="184" height="100" src="{{ MEDIA_URL }}{{ org.image }}"/>
                                            <div class="score">
                                                <div class="circle">
                                                    <h2>{{ org.tag }}</h2>
                                                </div>
                                            </div>
                                        </div>
                                        <p><span class="key" title="{{ org.name }}">{{ org.name }}</span></p>
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block foot_js %}
    <script type="text/javascript" src="{% static 'js/index.js' %}"></script>
{% endblock %}

templates/link_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>链接失效</title>
</head>
<body>
<p>链接失效！</p>
</body>
</html>

templates/org_base.html
<!DOCTYPE html>
<html>

{% load staticfiles %}

<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>{% block title %}机构首页{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/base.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/learn-less.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/common-less.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">

    {% block css %}{% endblock %}

    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>

    {% block head_js %}{% endblock %}

</head>
<body>
<section class="headerwrap headerwrap2">
    <header>
		<div  class="header2 header">
            <div class="top">
                <!--登录后跳转，显示个人中心和消息图标-->
                {% if request.user.is_authenticated %}
                    <div class="wp">
                        <div class="fl"><p>服务电话：<b>33333333</b></p></div>
                        <div class="personal">
                            <dl class="user fr">
                                <dd>{{ request.user.username }}<img class="down fr" src="{% static 'images/top_down.png' %}"/></dd>
                                <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
                            </dl>
                            <div class="userdetail">
                                <dl>
                                    <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
                                    <dd>
                                        <h2>{{ request.user.username }}</h2>
                                        {# <p>{{ request.user.username }}</p>#}
                                    </dd>
                                </dl>
                                <div class="btn">
                                    <a class="personcenter fl" href="{% url 'user:user_info' %}">进入个人中心</a>
                                    <a class="fr" href="{% url 'logout' %}">退出</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <a href="{% url 'user:user_mymessage' %}">
                        <div class="msg-num"> <span id="MsgNum">{{ request.user.get_unread_msgs }}</span></div>
                    </a>
                {#未登录时，显示注册与登录按钮#}
                {% else %}
                    <div class="wp">
                        <div class="fl"><p>服务电话：<b>33333333</b></p></div>
                        <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">注册</a>
                        <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">登录</a>
                    </div>
                {% endif %}
            </div>
    <div class="middle companyheader">
        <div class="wp">
            <img class="fl" style="width: 112px;height: 103px" src="{{ MEDIA_URL }}{{ course_org.image }}"/>
            <div class="head fl">
                <h1>
                    萌课网
                    <img src="{% static 'images/authentication.png' %}"/>
                    <img src="{% static 'images/gold.png' %}"/>
                </h1>
                <p class="fl">
                    <span class="fl" style="margin-top:8px;color:#848484;">推荐指数： </span>
                    <span class="precision company-credit" data-star-scope="5.0"></span>
                    <span class="key">5.0</span>
                </p>
            </div>
            <div class="btn fr collectionbtn  notlogin
                 "data-favid="22" data-fav-type="1">
                 {% if has_fav %}
                     取消收藏
                 {% else %}
                     收藏
                 {% endif %}
            </div>

        </div>
    </div>
			</div>
    </header>
</section>
<section>
	<div class="wp">
		<ul  class="crumbs">
            <li><a href="{% url 'index' %}">首页</a>></li>
			<li><a href="{% url 'org:org_list' %}">课程机构</a>></li>
			<li>{% block page_path %}机构首页{% endblock %}({{ course_org.name }})</li>
		</ul>
	</div>
</section>

<section>
	<div class="wp list personal_list comp">
		<div class="left">
			<ul>
				<li class="{% if request.path|slice:'9' == '/org/home' %}active2{% endif %}"><a href="{% url 'org:org_home' course_org.id %}">机构首页</a></li>
                <li class="{% if request.path|slice:'11' == '/org/course' %}active2{% endif %}"><a href="{% url 'org:org_course' course_org.id %}">机构课程</a></li>
                <li class="{% if request.path|slice:'9' == '/org/desc' %}active2{% endif %}"><a href="{% url 'org:org_desc' course_org.id %}">机构介绍</a></li>
                <li class="{% if request.path|slice:'12' == '/org/teacher' %}active2{% endif %}"><a href="{% url 'org:org_teacher' course_org.id %}">机构讲师</a></li>
			</ul>
		</div>

    {% block right_form %}
    {% endblock %}

</section>
<!--sidebar start-->
<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<!--sidebar end-->
<!--header start-->
</div>
<!--弹出省省市-->
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>

<script type="text/javascript" src="{% static 'js/plugins/jquery.raty.js' %}"></script>
<script type="text/javascript">
//收藏分享
function add_fav(current_elem, fav_id, fav_type){
    $.ajax({
        cache: false,
        type: "POST",
        url:"{% url 'org:add_fav' %}",
        data:{'fav_id':fav_id, 'fav_type':fav_type},
        async: true,
        beforeSend:function(xhr, settings){
            xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
        },
        success: function(data) {
            if(data.status == 'fail'){
                if(data.msg == '用户未登录'){
                    window.location.href="{% url 'login' %}";
                }else{
                    alert(data.msg)
                }

            }else if(data.status == 'success'){
                current_elem.text(data.msg)
            }
        },
    });
}

$('.collectionbtn').on('click', function(){
    add_fav($(this), {{ course_org.id }}, 'org');
});

$(function(){
    var $precision = $('.precision'),
        score = $precision.attr('data-star-scope'),
        option =  {
                    half		: true,
                    path		: '{% static 'images/' %}',
                    precision	: true,
                    size		: 24,
                    starOff		: 'g_star.png',
                    starOn		: 'r_star.png',
                    starHalf	: 'h_star.png',
                    hints       : ['极差', '差', '一般', '好评', '非常满意'],
                    noRatedMsg  : '暂时还未获得评价！',
                    readOnly    : true,
                    score       : score
                };
    $precision.raty(option);

    $('.jsFavBtn').on('click', function(){
        var type = $(this).attr('data-fav-type');
        if(type == '1'){
            favPraise($(this), 'fav' ,1 , '收藏');

        }else if(type == '3'){
            favPraise($(this), 'fav' ,3 );

        }else if(type == '11'){
            favPraise($(this), 'pra', 1);

        }else if(type == '4'){
            favPraise($(this), 'fav' ,4 );

        }
    });
})
</script>


<script type="text/javascript">
$(function() {
    $('.recordbtn1').click(function(){
        $('.recordbox1').show();
    });
    $('.recordbtn2').click(function(){
        $('.recordbox2').show();
    });

    $('.imgslide').unslider({
        speed: 500,               //  The speed to animate each slide (in milliseconds)
        delay: 3000,              //  The delay between slide animations (in milliseconds)
        complete: function() {},  //  A function that gets called after every slide animation
        keys: true,               //  Enable keyboard (left, right) arrow shortcuts
        dots: true,               //  Display dot navigation
        fluid: false              //  Support responsive design. May break non-responsive designs
    });
    var unslider = $('.imgslide').unslider();
    $('.unslider-arrow').click(function() {
        var fn = this.className.split(' ')[1];
        unslider.data('unslider')[fn]();
    });
});
</script>


<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script src="{% static 'js/deco-common.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}"  type="text/javascript"></script>
<script src="{% static 'js/deco-common.js' %}"  type="text/javascript"></script>
<script type="text/javascript" src="{% static 'js/index.js' %}"></script>


</body>
</html>

templates/usercenter-fav-course.html
{% extends 'usercenter-base.html' %}
{% load staticfiles %}

{% block title %}我的收藏 - 萌学在线网{% endblock %}

{% block bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'user:user_info' %}">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
{% endblock %}


{% block right_content %}
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li><a href="{% url 'user:user_myfav_org' %}">课程机构</a> </li>
                        <li><a href="{% url 'user:user_myfav_teacher' %}">授课教师 </a></li>
                        <li class="active"><a href="{% url 'user:user_myfav_course' %}">公开课程</a></li>
                    </ul>

                </div>
                <div class="companycenter">
                    <div class="group_list brief">
                        {% for course in myfav_courses %}
                            <div class="module1_5 box">
                                <a href="{% url 'course:course_detail' course.id %}">
                                    <img width="214" height="190" src="{{ MEDIA_URL }}{{ course.image }}"/>
                                </a>
                                <div class="des">
                                    <a href="{% url 'course:course_detail' course.id %}"><h2>{{ course.name }}</h2></a>
                                    <span class="fl">时长：<i class="key">{{ course.learn_times }}</i></span>
                                    <span class="fr">学习人数：{{ course.students }}</span>
                                </div>
                                <div class="bottom">
                                    <span class="fl">{{ course.course_org.name }}</span>
                                    <span class="delete-group fr jsDeleteFav_course" data-favid="{{ course.id }}"></span>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
{% endblock %}